title: OPUS Tuition
email: opus.tuitioncentre@gmail.com
description: >-
  OPUS Tuition provides private English, Math, and Science tuition for primary
  and secondary students in Singapore, combining personalised home learning
  with structured resources and progress tracking.
url: "https://opustuition.com"
baseurl: ""
timezone: Asia/Singapore

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
